// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jqeK6bba4WRfQXoAUcny0lZ6RayhETQ',
    appId: '1:558164732926:web:0ffde197f4f313798deeaf',
    messagingSenderId: '558164732926',
    projectId: 'base-8a533',
    authDomain: 'base-8a533.firebaseapp.com',
    databaseURL: 'https://base-8a533-default-rtdb.firebaseio.com',
    storageBucket: 'base-8a533.appspot.com',
    measurementId: 'G-7RV8SVBGX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYiBZfGAuzXfW3xUty5cECmarwkI0mE3Q',
    appId: '1:558164732926:android:258ed777a777d9748deeaf',
    messagingSenderId: '558164732926',
    projectId: 'base-8a533',
    databaseURL: 'https://base-8a533-default-rtdb.firebaseio.com',
    storageBucket: 'base-8a533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyo4btGiobA5jmz6qWw-vdtk2G7Lkyxk',
    appId: '1:558164732926:ios:1eec51b553dabe298deeaf',
    messagingSenderId: '558164732926',
    projectId: 'base-8a533',
    databaseURL: 'https://base-8a533-default-rtdb.firebaseio.com',
    storageBucket: 'base-8a533.appspot.com',
    iosBundleId: 'com.example.proyectocitasReparado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlyo4btGiobA5jmz6qWw-vdtk2G7Lkyxk',
    appId: '1:558164732926:ios:1eec51b553dabe298deeaf',
    messagingSenderId: '558164732926',
    projectId: 'base-8a533',
    databaseURL: 'https://base-8a533-default-rtdb.firebaseio.com',
    storageBucket: 'base-8a533.appspot.com',
    iosBundleId: 'com.example.proyectocitasReparado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-jqeK6bba4WRfQXoAUcny0lZ6RayhETQ',
    appId: '1:558164732926:web:d3fdf02d68ede4328deeaf',
    messagingSenderId: '558164732926',
    projectId: 'base-8a533',
    authDomain: 'base-8a533.firebaseapp.com',
    databaseURL: 'https://base-8a533-default-rtdb.firebaseio.com',
    storageBucket: 'base-8a533.appspot.com',
    measurementId: 'G-ZQK910D0LV',
  );

}